# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # using major version aliases

  # aliased to 5.2.17
  - 5.2
  - 5.3 
  - 5.4


# execute any number of scripts before the test run, custom env's are available as variables
before_script:
  chmod 777 cache;
  chmod +x ./tests/runtests.py;

# omitting "script:" will default to phpunit
script: tests/runtests.py --unit --regression --print-fail-log --quiet

